FROM golang:alpine as builder
RUN apk update && apk add git
COPY ./ /go/src/github.com/kartz/ratings/build
WORKDIR /go/src/github.com/kartz/ratings/build
RUN go get ./ && \
  CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .

FROM alpine
COPY --from=builder /go/src/github.com/kartz/ratings/build/main /app/
WORKDIR /app
CMD ["./main"]